// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/SmileOutlined';
export default { SmileOutlined };
