apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: knowledge-base
  name: deployment-knowledge-base-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-knowledge-base-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-knowledge-base-server
    spec:
      containers:
      - image: harbor.dev.meshlake.com:8443/meshlake/knowledge-base-server:0.0.1
        imagePullPolicy: Always
        name: app-knowledge-base-server
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: AZURE_OPENAI_API_KEY
          value: "49c6eee59eb642f29857eb571b0fb729"
        - name: AZURE_OPENAI_API_BASE
          value: "https://seedlings.openai.azure.com/"
        - name: MYSQL_ADDRESS
          value: "mysql.infra.svc.cluster.local:3306"
        - name: MYSQL_DATABASE
          value: "knowledge_base"
        - name: MYSQL_USERNAME
          value: "root"
        - name: MYSQL_PASSWORD
          value: "3vzN@qHktG!LbzV3"
        - name: SUPABASE_SERVICE_ROLE_KEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlicHhja2hjd21jY3d4YWd2Zm9iIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4NDIyNjk1MywiZXhwIjoxOTk5ODAyOTUzfQ.TafzsCMDmN1AFESpRmJeyCPWpeBCB91P8yecC1KjCu8"
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlicHhja2hjd21jY3d4YWd2Zm9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODQyMjY5NTMsImV4cCI6MTk5OTgwMjk1M30.ALYAnwISKrQ3W1gUgrbWtOsmjDAHn20sn7T_mdG8b70"
        - name: NEXT_PUBLIC_SUPABASE_URL
          value: "https://ybpxckhcwmccwxagvfob.supabase.co"
        - name: AWS_ACCESS_KEY_ID
          value: "AKIA5ZFNLPIQAAZBXN4J"
        - name: AWS_SECRET_ACCESS_KEY
          value: "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"
        - name:  AWS_DEFAULT_REGION
          value: cn-northwest-1
        - name: CHAT_SERVICE_BASE_URL
          value: https://chat.meshlake.com
        - name: WECHAT_BOT_SERVER
          value: http://service-wechat-bot.knowledge-base.svc.cluster.local
      imagePullSecrets:
          - name: meshlake-harbor-auth
---
apiVersion: v1
kind: Service
metadata:
  namespace: knowledge-base
  name: service-knowledge-base-server
spec:
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-knowledge-base-server