apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: knowledge-base-test
  name: deployment-knowledge-base-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-knowledge-base-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-knowledge-base-server
    spec:
      containers:
      - image: harbor.dev.meshlake.com:8443/meshlake/knowledge-base-server:test
        imagePullPolicy: Always
        name: app-knowledge-base-server
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: AZURE_OPENAI_API_KEY
          value: "49c6eee59eb642f29857eb571b0fb729"
        - name: AZURE_OPENAI_API_BASE
          value: "https://seedlings.openai.azure.com/"
        - name: MYSQL_ADDRESS
          value: "mysql.infra.svc.cluster.local:3306"
        - name: MYSQL_DATABASE
          value: "knowledge_base_test"
        - name: MYSQL_USERNAME
          value: "root"
        - name: MYSQL_PASSWORD
          value: "3vzN@qHktG!LbzV3"
        - name: SUPABASE_SERVICE_ROLE_KEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oZWlvd2R6cnpsbnBkc2RwcXl4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4NzkzOTg4NiwiZXhwIjoyMDAzNTE1ODg2fQ.1irXrGwamJ001EDMfqaiWrqC4zxZoz6UXKuzTJXb0T4"
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oZWlvd2R6cnpsbnBkc2RwcXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODc5Mzk4ODYsImV4cCI6MjAwMzUxNTg4Nn0.7NWl2AqIIeI8JVudKGhagWsY8u1niRXp4RumhTezprE"
        - name: NEXT_PUBLIC_SUPABASE_URL
          value: "https://mheiowdzrzlnpdsdpqyx.supabase.co"
        - name: AWS_ACCESS_KEY_ID
          value: "AKIA5ZFNLPIQAAZBXN4J"
        - name: AWS_SECRET_ACCESS_KEY
          value: "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"
        - name:  AWS_DEFAULT_REGION
          value: cn-northwest-1
        - name: CHAT_SERVICE_BASE_URL
          value: https://chat-test.meshlake.com
        - name: WECHAT_BOT_SERVER
          value: http://service-wechat-bot.knowledge-base-test.svc.cluster.local
        - name: OPENAI_API_KEY
          value: "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"
      imagePullSecrets:
          - name: meshlake-harbor-auth
---
apiVersion: v1
kind: Service
metadata:
  namespace: knowledge-base-test
  name: service-knowledge-base-server
spec:
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-knowledge-base-server