// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/node_modules/.pnpm/@umijs+renderer-react@4.0.66_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/node_modules/.pnpm/@umijs+renderer-react@4.0.66_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/node_modules/.pnpm/umi@4.0.66_@babel+core@7.21.4_@types+node@18.16.0_@types+react@18.0.28_eslint@8.35.0_jest@29._rhudjst3wah6slbkwvz4u7jwba/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/src/.umi-test/plugin-access';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/src/.umi-test/plugin-locale';
export { Provider, useModel } from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/src/.umi-test/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/src/.umi-test/plugin-request';
// plugins types.d.ts
export * from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/src/.umi-test/plugin-access/types.d';
export * from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/src/.umi-test/plugin-antd/types.d';
export * from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/src/.umi-test/plugin-layout/types.d';
export * from '/Users/zhaofengnian/Desktop/meshlake-workspace/doc-search-management/FrontEnd/src/.umi-test/plugin-request/types.d';
